export {
  ArchiveIcon as ArchiveReasonsIcon,
  BrowserIcon as JobPostingIcon,
  BriefcaseIcon as CloseJobReasonsIcon,
  CalendarSlashIcon as CancelRescheduleReasonsIcon,
  ChatCenteredTextIcon as FeedbackFormIcon,
  ClipboardTextIcon as ApplicationFormIcon,
  ClipboardTextIcon as ApplicationReviewIcon,
  ListChecksIcon as EvaluationCriteriaIcon,
  ListNumbersIcon as InterviewPlanIcon,
  ListPlusIcon as CustomFieldsIcon,
  NetworkIcon as DepartmentsAndTeamsIcon,
  SlidersHorizontalIcon as JobSettingsIcon,
  UsersThreeIcon as HiringTeamIcon,
  WalletIcon as JobFundsIcon,
} from '@phosphor-icons/react';
