export {
  ArchiveIcon as ArchiveReasonsIcon,
  BriefcaseIcon as CloseJobReasonsIcon,
  BrowserIcon as JobPostingIcon,
  CalendarSlashIcon as CancelRescheduleReasonsIcon,
  ChatCenteredTextIcon as FeedbackFormIcon,
  ClipboardTextIcon as ApplicationFormIcon,
  ClipboardTextIcon as ApplicationReviewIcon,
  ListChecksIcon as EvaluationCriteriaIcon,
  ListNumbersIcon as InterviewPlanIcon,
  ListPlusIcon as CustomFieldsIcon,
  NetworkIcon as DepartmentsAndTeamsIcon,
  SlidersHorizontalIcon as JobSettingsIcon,
  UsersThreeIcon as HiringTeamIcon,
  WalletIcon as CommitmentFundsIcon,
} from '@phosphor-icons/react';
