/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgCreateRouteImport } from './routes/org/create'
import { Route as OrgOrgIdRouteImport } from './routes/org/$orgId'
import { Route as OrgOrgIdIndexRouteImport } from './routes/org/$orgId/index'
import { Route as OrgOrgIdSettingsRouteImport } from './routes/org/$orgId/settings'
import { Route as OrgOrgIdPipelineRouteImport } from './routes/org/$orgId/pipeline'
import { Route as OrgOrgIdOrganizationRouteImport } from './routes/org/$orgId/organization'
import { Route as OrgOrgIdSettingsIndexRouteImport } from './routes/org/$orgId/settings/index'
import { Route as OrgOrgIdOrganizationIndexRouteImport } from './routes/org/$orgId/organization/index'
import { Route as OrgOrgIdJobsIndexRouteImport } from './routes/org/$orgId/jobs/index'
import { Route as OrgOrgIdSettingsCalendarRouteImport } from './routes/org/$orgId/settings/calendar'
import { Route as OrgOrgIdOrganizationTagsRouteImport } from './routes/org/$orgId/organization/tags'
import { Route as OrgOrgIdOrganizationMembersRouteImport } from './routes/org/$orgId/organization/members'
import { Route as OrgOrgIdOrganizationLocationsRouteImport } from './routes/org/$orgId/organization/locations'
import { Route as OrgOrgIdOrganizationJobTemplatesRouteImport } from './routes/org/$orgId/organization/job-templates'
import { Route as OrgOrgIdOrganizationInterviewsRouteImport } from './routes/org/$orgId/organization/interviews'
import { Route as OrgOrgIdOrganizationInterviewReasonsRouteImport } from './routes/org/$orgId/organization/interview-reasons'
import { Route as OrgOrgIdOrganizationInterviewPlansRouteImport } from './routes/org/$orgId/organization/interview-plans'
import { Route as OrgOrgIdOrganizationFundsRouteImport } from './routes/org/$orgId/organization/funds'
import { Route as OrgOrgIdOrganizationEmailTemplatesRouteImport } from './routes/org/$orgId/organization/email-templates'
import { Route as OrgOrgIdOrganizationDepartmentsRouteImport } from './routes/org/$orgId/organization/departments'
import { Route as OrgOrgIdOrganizationDataPrivacyRouteImport } from './routes/org/$orgId/organization/data-privacy'
import { Route as OrgOrgIdOrganizationCustomFieldsRouteImport } from './routes/org/$orgId/organization/custom-fields'
import { Route as OrgOrgIdOrganizationCompanyRouteImport } from './routes/org/$orgId/organization/company'
import { Route as OrgOrgIdOrganizationCloseReasonsRouteImport } from './routes/org/$orgId/organization/close-reasons'
import { Route as OrgOrgIdOrganizationArchiveReasonsRouteImport } from './routes/org/$orgId/organization/archive-reasons'
import { Route as OrgOrgIdJobsJobIdRouteImport } from './routes/org/$orgId/jobs/$jobId'
import { Route as OrgOrgIdOrganizationJobTemplatesIndexRouteImport } from './routes/org/$orgId/organization/job-templates/index'
import { Route as OrgOrgIdOrganizationInterviewsIndexRouteImport } from './routes/org/$orgId/organization/interviews/index'
import { Route as OrgOrgIdOrganizationInterviewPlansIndexRouteImport } from './routes/org/$orgId/organization/interview-plans/index'
import { Route as OrgOrgIdOrganizationFeedbackFormsIndexRouteImport } from './routes/org/$orgId/organization/feedback-forms/index'
import { Route as OrgOrgIdOrganizationApplicationFormsIndexRouteImport } from './routes/org/$orgId/organization/application-forms/index'
import { Route as OrgOrgIdJobsJobIdPipelineRouteImport } from './routes/org/$orgId/jobs/$jobId/pipeline'
import { Route as OrgOrgIdJobsJobIdInterviewPlanRouteImport } from './routes/org/$orgId/jobs/$jobId/interview-plan'
import { Route as OrgOrgIdJobsJobIdHiringTeamRouteImport } from './routes/org/$orgId/jobs/$jobId/hiring-team'
import { Route as OrgOrgIdJobsJobIdDetailsRouteImport } from './routes/org/$orgId/jobs/$jobId/details'
import { Route as OrgOrgIdJobsJobIdDescriptionRouteImport } from './routes/org/$orgId/jobs/$jobId/description'
import { Route as OrgOrgIdJobsJobIdCriteriaRouteImport } from './routes/org/$orgId/jobs/$jobId/criteria'
import { Route as OrgOrgIdJobsJobIdApplicationFormRouteImport } from './routes/org/$orgId/jobs/$jobId/application-form'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgCreateRoute = OrgCreateRouteImport.update({
  id: '/org/create',
  path: '/org/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdRoute = OrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdIndexRoute = OrgOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSettingsRoute = OrgOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdPipelineRoute = OrgOrgIdPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdOrganizationRoute = OrgOrgIdOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSettingsIndexRoute = OrgOrgIdSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgIdSettingsRoute,
} as any)
const OrgOrgIdOrganizationIndexRoute =
  OrgOrgIdOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdJobsIndexRoute = OrgOrgIdJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdSettingsCalendarRoute =
  OrgOrgIdSettingsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => OrgOrgIdSettingsRoute,
  } as any)
const OrgOrgIdOrganizationTagsRoute =
  OrgOrgIdOrganizationTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationMembersRoute =
  OrgOrgIdOrganizationMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationLocationsRoute =
  OrgOrgIdOrganizationLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationJobTemplatesRoute =
  OrgOrgIdOrganizationJobTemplatesRouteImport.update({
    id: '/job-templates',
    path: '/job-templates',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationInterviewsRoute =
  OrgOrgIdOrganizationInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationInterviewReasonsRoute =
  OrgOrgIdOrganizationInterviewReasonsRouteImport.update({
    id: '/interview-reasons',
    path: '/interview-reasons',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationInterviewPlansRoute =
  OrgOrgIdOrganizationInterviewPlansRouteImport.update({
    id: '/interview-plans',
    path: '/interview-plans',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationFundsRoute =
  OrgOrgIdOrganizationFundsRouteImport.update({
    id: '/funds',
    path: '/funds',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationEmailTemplatesRoute =
  OrgOrgIdOrganizationEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationDepartmentsRoute =
  OrgOrgIdOrganizationDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationDataPrivacyRoute =
  OrgOrgIdOrganizationDataPrivacyRouteImport.update({
    id: '/data-privacy',
    path: '/data-privacy',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationCustomFieldsRoute =
  OrgOrgIdOrganizationCustomFieldsRouteImport.update({
    id: '/custom-fields',
    path: '/custom-fields',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationCompanyRoute =
  OrgOrgIdOrganizationCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationCloseReasonsRoute =
  OrgOrgIdOrganizationCloseReasonsRouteImport.update({
    id: '/close-reasons',
    path: '/close-reasons',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationArchiveReasonsRoute =
  OrgOrgIdOrganizationArchiveReasonsRouteImport.update({
    id: '/archive-reasons',
    path: '/archive-reasons',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdJobsJobIdRoute = OrgOrgIdJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => OrgOrgIdRoute,
} as any)
const OrgOrgIdOrganizationJobTemplatesIndexRoute =
  OrgOrgIdOrganizationJobTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgOrgIdOrganizationJobTemplatesRoute,
  } as any)
const OrgOrgIdOrganizationInterviewsIndexRoute =
  OrgOrgIdOrganizationInterviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgOrgIdOrganizationInterviewsRoute,
  } as any)
const OrgOrgIdOrganizationInterviewPlansIndexRoute =
  OrgOrgIdOrganizationInterviewPlansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgOrgIdOrganizationInterviewPlansRoute,
  } as any)
const OrgOrgIdOrganizationFeedbackFormsIndexRoute =
  OrgOrgIdOrganizationFeedbackFormsIndexRouteImport.update({
    id: '/feedback-forms/',
    path: '/feedback-forms/',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdOrganizationApplicationFormsIndexRoute =
  OrgOrgIdOrganizationApplicationFormsIndexRouteImport.update({
    id: '/application-forms/',
    path: '/application-forms/',
    getParentRoute: () => OrgOrgIdOrganizationRoute,
  } as any)
const OrgOrgIdJobsJobIdPipelineRoute =
  OrgOrgIdJobsJobIdPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => OrgOrgIdJobsJobIdRoute,
  } as any)
const OrgOrgIdJobsJobIdInterviewPlanRoute =
  OrgOrgIdJobsJobIdInterviewPlanRouteImport.update({
    id: '/interview-plan',
    path: '/interview-plan',
    getParentRoute: () => OrgOrgIdJobsJobIdRoute,
  } as any)
const OrgOrgIdJobsJobIdHiringTeamRoute =
  OrgOrgIdJobsJobIdHiringTeamRouteImport.update({
    id: '/hiring-team',
    path: '/hiring-team',
    getParentRoute: () => OrgOrgIdJobsJobIdRoute,
  } as any)
const OrgOrgIdJobsJobIdDetailsRoute =
  OrgOrgIdJobsJobIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => OrgOrgIdJobsJobIdRoute,
  } as any)
const OrgOrgIdJobsJobIdDescriptionRoute =
  OrgOrgIdJobsJobIdDescriptionRouteImport.update({
    id: '/description',
    path: '/description',
    getParentRoute: () => OrgOrgIdJobsJobIdRoute,
  } as any)
const OrgOrgIdJobsJobIdCriteriaRoute =
  OrgOrgIdJobsJobIdCriteriaRouteImport.update({
    id: '/criteria',
    path: '/criteria',
    getParentRoute: () => OrgOrgIdJobsJobIdRoute,
  } as any)
const OrgOrgIdJobsJobIdApplicationFormRoute =
  OrgOrgIdJobsJobIdApplicationFormRouteImport.update({
    id: '/application-form',
    path: '/application-form',
    getParentRoute: () => OrgOrgIdJobsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/org/create': typeof OrgCreateRoute
  '/org/$orgId/organization': typeof OrgOrgIdOrganizationRouteWithChildren
  '/org/$orgId/pipeline': typeof OrgOrgIdPipelineRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRouteWithChildren
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/jobs/$jobId': typeof OrgOrgIdJobsJobIdRouteWithChildren
  '/org/$orgId/organization/archive-reasons': typeof OrgOrgIdOrganizationArchiveReasonsRoute
  '/org/$orgId/organization/close-reasons': typeof OrgOrgIdOrganizationCloseReasonsRoute
  '/org/$orgId/organization/company': typeof OrgOrgIdOrganizationCompanyRoute
  '/org/$orgId/organization/custom-fields': typeof OrgOrgIdOrganizationCustomFieldsRoute
  '/org/$orgId/organization/data-privacy': typeof OrgOrgIdOrganizationDataPrivacyRoute
  '/org/$orgId/organization/departments': typeof OrgOrgIdOrganizationDepartmentsRoute
  '/org/$orgId/organization/email-templates': typeof OrgOrgIdOrganizationEmailTemplatesRoute
  '/org/$orgId/organization/funds': typeof OrgOrgIdOrganizationFundsRoute
  '/org/$orgId/organization/interview-plans': typeof OrgOrgIdOrganizationInterviewPlansRouteWithChildren
  '/org/$orgId/organization/interview-reasons': typeof OrgOrgIdOrganizationInterviewReasonsRoute
  '/org/$orgId/organization/interviews': typeof OrgOrgIdOrganizationInterviewsRouteWithChildren
  '/org/$orgId/organization/job-templates': typeof OrgOrgIdOrganizationJobTemplatesRouteWithChildren
  '/org/$orgId/organization/locations': typeof OrgOrgIdOrganizationLocationsRoute
  '/org/$orgId/organization/members': typeof OrgOrgIdOrganizationMembersRoute
  '/org/$orgId/organization/tags': typeof OrgOrgIdOrganizationTagsRoute
  '/org/$orgId/settings/calendar': typeof OrgOrgIdSettingsCalendarRoute
  '/org/$orgId/jobs': typeof OrgOrgIdJobsIndexRoute
  '/org/$orgId/organization/': typeof OrgOrgIdOrganizationIndexRoute
  '/org/$orgId/settings/': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/jobs/$jobId/application-form': typeof OrgOrgIdJobsJobIdApplicationFormRoute
  '/org/$orgId/jobs/$jobId/criteria': typeof OrgOrgIdJobsJobIdCriteriaRoute
  '/org/$orgId/jobs/$jobId/description': typeof OrgOrgIdJobsJobIdDescriptionRoute
  '/org/$orgId/jobs/$jobId/details': typeof OrgOrgIdJobsJobIdDetailsRoute
  '/org/$orgId/jobs/$jobId/hiring-team': typeof OrgOrgIdJobsJobIdHiringTeamRoute
  '/org/$orgId/jobs/$jobId/interview-plan': typeof OrgOrgIdJobsJobIdInterviewPlanRoute
  '/org/$orgId/jobs/$jobId/pipeline': typeof OrgOrgIdJobsJobIdPipelineRoute
  '/org/$orgId/organization/application-forms': typeof OrgOrgIdOrganizationApplicationFormsIndexRoute
  '/org/$orgId/organization/feedback-forms': typeof OrgOrgIdOrganizationFeedbackFormsIndexRoute
  '/org/$orgId/organization/interview-plans/': typeof OrgOrgIdOrganizationInterviewPlansIndexRoute
  '/org/$orgId/organization/interviews/': typeof OrgOrgIdOrganizationInterviewsIndexRoute
  '/org/$orgId/organization/job-templates/': typeof OrgOrgIdOrganizationJobTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/org/create': typeof OrgCreateRoute
  '/org/$orgId/pipeline': typeof OrgOrgIdPipelineRoute
  '/org/$orgId': typeof OrgOrgIdIndexRoute
  '/org/$orgId/jobs/$jobId': typeof OrgOrgIdJobsJobIdRouteWithChildren
  '/org/$orgId/organization/archive-reasons': typeof OrgOrgIdOrganizationArchiveReasonsRoute
  '/org/$orgId/organization/close-reasons': typeof OrgOrgIdOrganizationCloseReasonsRoute
  '/org/$orgId/organization/company': typeof OrgOrgIdOrganizationCompanyRoute
  '/org/$orgId/organization/custom-fields': typeof OrgOrgIdOrganizationCustomFieldsRoute
  '/org/$orgId/organization/data-privacy': typeof OrgOrgIdOrganizationDataPrivacyRoute
  '/org/$orgId/organization/departments': typeof OrgOrgIdOrganizationDepartmentsRoute
  '/org/$orgId/organization/email-templates': typeof OrgOrgIdOrganizationEmailTemplatesRoute
  '/org/$orgId/organization/funds': typeof OrgOrgIdOrganizationFundsRoute
  '/org/$orgId/organization/interview-reasons': typeof OrgOrgIdOrganizationInterviewReasonsRoute
  '/org/$orgId/organization/locations': typeof OrgOrgIdOrganizationLocationsRoute
  '/org/$orgId/organization/members': typeof OrgOrgIdOrganizationMembersRoute
  '/org/$orgId/organization/tags': typeof OrgOrgIdOrganizationTagsRoute
  '/org/$orgId/settings/calendar': typeof OrgOrgIdSettingsCalendarRoute
  '/org/$orgId/jobs': typeof OrgOrgIdJobsIndexRoute
  '/org/$orgId/organization': typeof OrgOrgIdOrganizationIndexRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/jobs/$jobId/application-form': typeof OrgOrgIdJobsJobIdApplicationFormRoute
  '/org/$orgId/jobs/$jobId/criteria': typeof OrgOrgIdJobsJobIdCriteriaRoute
  '/org/$orgId/jobs/$jobId/description': typeof OrgOrgIdJobsJobIdDescriptionRoute
  '/org/$orgId/jobs/$jobId/details': typeof OrgOrgIdJobsJobIdDetailsRoute
  '/org/$orgId/jobs/$jobId/hiring-team': typeof OrgOrgIdJobsJobIdHiringTeamRoute
  '/org/$orgId/jobs/$jobId/interview-plan': typeof OrgOrgIdJobsJobIdInterviewPlanRoute
  '/org/$orgId/jobs/$jobId/pipeline': typeof OrgOrgIdJobsJobIdPipelineRoute
  '/org/$orgId/organization/application-forms': typeof OrgOrgIdOrganizationApplicationFormsIndexRoute
  '/org/$orgId/organization/feedback-forms': typeof OrgOrgIdOrganizationFeedbackFormsIndexRoute
  '/org/$orgId/organization/interview-plans': typeof OrgOrgIdOrganizationInterviewPlansIndexRoute
  '/org/$orgId/organization/interviews': typeof OrgOrgIdOrganizationInterviewsIndexRoute
  '/org/$orgId/organization/job-templates': typeof OrgOrgIdOrganizationJobTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/org/$orgId': typeof OrgOrgIdRouteWithChildren
  '/org/create': typeof OrgCreateRoute
  '/org/$orgId/organization': typeof OrgOrgIdOrganizationRouteWithChildren
  '/org/$orgId/pipeline': typeof OrgOrgIdPipelineRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRouteWithChildren
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/jobs/$jobId': typeof OrgOrgIdJobsJobIdRouteWithChildren
  '/org/$orgId/organization/archive-reasons': typeof OrgOrgIdOrganizationArchiveReasonsRoute
  '/org/$orgId/organization/close-reasons': typeof OrgOrgIdOrganizationCloseReasonsRoute
  '/org/$orgId/organization/company': typeof OrgOrgIdOrganizationCompanyRoute
  '/org/$orgId/organization/custom-fields': typeof OrgOrgIdOrganizationCustomFieldsRoute
  '/org/$orgId/organization/data-privacy': typeof OrgOrgIdOrganizationDataPrivacyRoute
  '/org/$orgId/organization/departments': typeof OrgOrgIdOrganizationDepartmentsRoute
  '/org/$orgId/organization/email-templates': typeof OrgOrgIdOrganizationEmailTemplatesRoute
  '/org/$orgId/organization/funds': typeof OrgOrgIdOrganizationFundsRoute
  '/org/$orgId/organization/interview-plans': typeof OrgOrgIdOrganizationInterviewPlansRouteWithChildren
  '/org/$orgId/organization/interview-reasons': typeof OrgOrgIdOrganizationInterviewReasonsRoute
  '/org/$orgId/organization/interviews': typeof OrgOrgIdOrganizationInterviewsRouteWithChildren
  '/org/$orgId/organization/job-templates': typeof OrgOrgIdOrganizationJobTemplatesRouteWithChildren
  '/org/$orgId/organization/locations': typeof OrgOrgIdOrganizationLocationsRoute
  '/org/$orgId/organization/members': typeof OrgOrgIdOrganizationMembersRoute
  '/org/$orgId/organization/tags': typeof OrgOrgIdOrganizationTagsRoute
  '/org/$orgId/settings/calendar': typeof OrgOrgIdSettingsCalendarRoute
  '/org/$orgId/jobs/': typeof OrgOrgIdJobsIndexRoute
  '/org/$orgId/organization/': typeof OrgOrgIdOrganizationIndexRoute
  '/org/$orgId/settings/': typeof OrgOrgIdSettingsIndexRoute
  '/org/$orgId/jobs/$jobId/application-form': typeof OrgOrgIdJobsJobIdApplicationFormRoute
  '/org/$orgId/jobs/$jobId/criteria': typeof OrgOrgIdJobsJobIdCriteriaRoute
  '/org/$orgId/jobs/$jobId/description': typeof OrgOrgIdJobsJobIdDescriptionRoute
  '/org/$orgId/jobs/$jobId/details': typeof OrgOrgIdJobsJobIdDetailsRoute
  '/org/$orgId/jobs/$jobId/hiring-team': typeof OrgOrgIdJobsJobIdHiringTeamRoute
  '/org/$orgId/jobs/$jobId/interview-plan': typeof OrgOrgIdJobsJobIdInterviewPlanRoute
  '/org/$orgId/jobs/$jobId/pipeline': typeof OrgOrgIdJobsJobIdPipelineRoute
  '/org/$orgId/organization/application-forms/': typeof OrgOrgIdOrganizationApplicationFormsIndexRoute
  '/org/$orgId/organization/feedback-forms/': typeof OrgOrgIdOrganizationFeedbackFormsIndexRoute
  '/org/$orgId/organization/interview-plans/': typeof OrgOrgIdOrganizationInterviewPlansIndexRoute
  '/org/$orgId/organization/interviews/': typeof OrgOrgIdOrganizationInterviewsIndexRoute
  '/org/$orgId/organization/job-templates/': typeof OrgOrgIdOrganizationJobTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/invite'
    | '/login'
    | '/signup'
    | '/org/$orgId'
    | '/org/create'
    | '/org/$orgId/organization'
    | '/org/$orgId/pipeline'
    | '/org/$orgId/settings'
    | '/org/$orgId/'
    | '/org/$orgId/jobs/$jobId'
    | '/org/$orgId/organization/archive-reasons'
    | '/org/$orgId/organization/close-reasons'
    | '/org/$orgId/organization/company'
    | '/org/$orgId/organization/custom-fields'
    | '/org/$orgId/organization/data-privacy'
    | '/org/$orgId/organization/departments'
    | '/org/$orgId/organization/email-templates'
    | '/org/$orgId/organization/funds'
    | '/org/$orgId/organization/interview-plans'
    | '/org/$orgId/organization/interview-reasons'
    | '/org/$orgId/organization/interviews'
    | '/org/$orgId/organization/job-templates'
    | '/org/$orgId/organization/locations'
    | '/org/$orgId/organization/members'
    | '/org/$orgId/organization/tags'
    | '/org/$orgId/settings/calendar'
    | '/org/$orgId/jobs'
    | '/org/$orgId/organization/'
    | '/org/$orgId/settings/'
    | '/org/$orgId/jobs/$jobId/application-form'
    | '/org/$orgId/jobs/$jobId/criteria'
    | '/org/$orgId/jobs/$jobId/description'
    | '/org/$orgId/jobs/$jobId/details'
    | '/org/$orgId/jobs/$jobId/hiring-team'
    | '/org/$orgId/jobs/$jobId/interview-plan'
    | '/org/$orgId/jobs/$jobId/pipeline'
    | '/org/$orgId/organization/application-forms'
    | '/org/$orgId/organization/feedback-forms'
    | '/org/$orgId/organization/interview-plans/'
    | '/org/$orgId/organization/interviews/'
    | '/org/$orgId/organization/job-templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/invite'
    | '/login'
    | '/signup'
    | '/org/create'
    | '/org/$orgId/pipeline'
    | '/org/$orgId'
    | '/org/$orgId/jobs/$jobId'
    | '/org/$orgId/organization/archive-reasons'
    | '/org/$orgId/organization/close-reasons'
    | '/org/$orgId/organization/company'
    | '/org/$orgId/organization/custom-fields'
    | '/org/$orgId/organization/data-privacy'
    | '/org/$orgId/organization/departments'
    | '/org/$orgId/organization/email-templates'
    | '/org/$orgId/organization/funds'
    | '/org/$orgId/organization/interview-reasons'
    | '/org/$orgId/organization/locations'
    | '/org/$orgId/organization/members'
    | '/org/$orgId/organization/tags'
    | '/org/$orgId/settings/calendar'
    | '/org/$orgId/jobs'
    | '/org/$orgId/organization'
    | '/org/$orgId/settings'
    | '/org/$orgId/jobs/$jobId/application-form'
    | '/org/$orgId/jobs/$jobId/criteria'
    | '/org/$orgId/jobs/$jobId/description'
    | '/org/$orgId/jobs/$jobId/details'
    | '/org/$orgId/jobs/$jobId/hiring-team'
    | '/org/$orgId/jobs/$jobId/interview-plan'
    | '/org/$orgId/jobs/$jobId/pipeline'
    | '/org/$orgId/organization/application-forms'
    | '/org/$orgId/organization/feedback-forms'
    | '/org/$orgId/organization/interview-plans'
    | '/org/$orgId/organization/interviews'
    | '/org/$orgId/organization/job-templates'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/invite'
    | '/login'
    | '/signup'
    | '/org/$orgId'
    | '/org/create'
    | '/org/$orgId/organization'
    | '/org/$orgId/pipeline'
    | '/org/$orgId/settings'
    | '/org/$orgId/'
    | '/org/$orgId/jobs/$jobId'
    | '/org/$orgId/organization/archive-reasons'
    | '/org/$orgId/organization/close-reasons'
    | '/org/$orgId/organization/company'
    | '/org/$orgId/organization/custom-fields'
    | '/org/$orgId/organization/data-privacy'
    | '/org/$orgId/organization/departments'
    | '/org/$orgId/organization/email-templates'
    | '/org/$orgId/organization/funds'
    | '/org/$orgId/organization/interview-plans'
    | '/org/$orgId/organization/interview-reasons'
    | '/org/$orgId/organization/interviews'
    | '/org/$orgId/organization/job-templates'
    | '/org/$orgId/organization/locations'
    | '/org/$orgId/organization/members'
    | '/org/$orgId/organization/tags'
    | '/org/$orgId/settings/calendar'
    | '/org/$orgId/jobs/'
    | '/org/$orgId/organization/'
    | '/org/$orgId/settings/'
    | '/org/$orgId/jobs/$jobId/application-form'
    | '/org/$orgId/jobs/$jobId/criteria'
    | '/org/$orgId/jobs/$jobId/description'
    | '/org/$orgId/jobs/$jobId/details'
    | '/org/$orgId/jobs/$jobId/hiring-team'
    | '/org/$orgId/jobs/$jobId/interview-plan'
    | '/org/$orgId/jobs/$jobId/pipeline'
    | '/org/$orgId/organization/application-forms/'
    | '/org/$orgId/organization/feedback-forms/'
    | '/org/$orgId/organization/interview-plans/'
    | '/org/$orgId/organization/interviews/'
    | '/org/$orgId/organization/job-templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  OrgOrgIdRoute: typeof OrgOrgIdRouteWithChildren
  OrgCreateRoute: typeof OrgCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/create': {
      id: '/org/create'
      path: '/org/create'
      fullPath: '/org/create'
      preLoaderRoute: typeof OrgCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId': {
      id: '/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof OrgOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/': {
      id: '/org/$orgId/'
      path: '/'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof OrgOrgIdIndexRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/settings': {
      id: '/org/$orgId/settings'
      path: '/settings'
      fullPath: '/org/$orgId/settings'
      preLoaderRoute: typeof OrgOrgIdSettingsRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/pipeline': {
      id: '/org/$orgId/pipeline'
      path: '/pipeline'
      fullPath: '/org/$orgId/pipeline'
      preLoaderRoute: typeof OrgOrgIdPipelineRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/organization': {
      id: '/org/$orgId/organization'
      path: '/organization'
      fullPath: '/org/$orgId/organization'
      preLoaderRoute: typeof OrgOrgIdOrganizationRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/settings/': {
      id: '/org/$orgId/settings/'
      path: '/'
      fullPath: '/org/$orgId/settings/'
      preLoaderRoute: typeof OrgOrgIdSettingsIndexRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/organization/': {
      id: '/org/$orgId/organization/'
      path: '/'
      fullPath: '/org/$orgId/organization/'
      preLoaderRoute: typeof OrgOrgIdOrganizationIndexRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/jobs/': {
      id: '/org/$orgId/jobs/'
      path: '/jobs'
      fullPath: '/org/$orgId/jobs'
      preLoaderRoute: typeof OrgOrgIdJobsIndexRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/settings/calendar': {
      id: '/org/$orgId/settings/calendar'
      path: '/calendar'
      fullPath: '/org/$orgId/settings/calendar'
      preLoaderRoute: typeof OrgOrgIdSettingsCalendarRouteImport
      parentRoute: typeof OrgOrgIdSettingsRoute
    }
    '/org/$orgId/organization/tags': {
      id: '/org/$orgId/organization/tags'
      path: '/tags'
      fullPath: '/org/$orgId/organization/tags'
      preLoaderRoute: typeof OrgOrgIdOrganizationTagsRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/members': {
      id: '/org/$orgId/organization/members'
      path: '/members'
      fullPath: '/org/$orgId/organization/members'
      preLoaderRoute: typeof OrgOrgIdOrganizationMembersRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/locations': {
      id: '/org/$orgId/organization/locations'
      path: '/locations'
      fullPath: '/org/$orgId/organization/locations'
      preLoaderRoute: typeof OrgOrgIdOrganizationLocationsRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/job-templates': {
      id: '/org/$orgId/organization/job-templates'
      path: '/job-templates'
      fullPath: '/org/$orgId/organization/job-templates'
      preLoaderRoute: typeof OrgOrgIdOrganizationJobTemplatesRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/interviews': {
      id: '/org/$orgId/organization/interviews'
      path: '/interviews'
      fullPath: '/org/$orgId/organization/interviews'
      preLoaderRoute: typeof OrgOrgIdOrganizationInterviewsRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/interview-reasons': {
      id: '/org/$orgId/organization/interview-reasons'
      path: '/interview-reasons'
      fullPath: '/org/$orgId/organization/interview-reasons'
      preLoaderRoute: typeof OrgOrgIdOrganizationInterviewReasonsRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/interview-plans': {
      id: '/org/$orgId/organization/interview-plans'
      path: '/interview-plans'
      fullPath: '/org/$orgId/organization/interview-plans'
      preLoaderRoute: typeof OrgOrgIdOrganizationInterviewPlansRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/funds': {
      id: '/org/$orgId/organization/funds'
      path: '/funds'
      fullPath: '/org/$orgId/organization/funds'
      preLoaderRoute: typeof OrgOrgIdOrganizationFundsRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/email-templates': {
      id: '/org/$orgId/organization/email-templates'
      path: '/email-templates'
      fullPath: '/org/$orgId/organization/email-templates'
      preLoaderRoute: typeof OrgOrgIdOrganizationEmailTemplatesRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/departments': {
      id: '/org/$orgId/organization/departments'
      path: '/departments'
      fullPath: '/org/$orgId/organization/departments'
      preLoaderRoute: typeof OrgOrgIdOrganizationDepartmentsRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/data-privacy': {
      id: '/org/$orgId/organization/data-privacy'
      path: '/data-privacy'
      fullPath: '/org/$orgId/organization/data-privacy'
      preLoaderRoute: typeof OrgOrgIdOrganizationDataPrivacyRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/custom-fields': {
      id: '/org/$orgId/organization/custom-fields'
      path: '/custom-fields'
      fullPath: '/org/$orgId/organization/custom-fields'
      preLoaderRoute: typeof OrgOrgIdOrganizationCustomFieldsRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/company': {
      id: '/org/$orgId/organization/company'
      path: '/company'
      fullPath: '/org/$orgId/organization/company'
      preLoaderRoute: typeof OrgOrgIdOrganizationCompanyRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/close-reasons': {
      id: '/org/$orgId/organization/close-reasons'
      path: '/close-reasons'
      fullPath: '/org/$orgId/organization/close-reasons'
      preLoaderRoute: typeof OrgOrgIdOrganizationCloseReasonsRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/archive-reasons': {
      id: '/org/$orgId/organization/archive-reasons'
      path: '/archive-reasons'
      fullPath: '/org/$orgId/organization/archive-reasons'
      preLoaderRoute: typeof OrgOrgIdOrganizationArchiveReasonsRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/jobs/$jobId': {
      id: '/org/$orgId/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/org/$orgId/jobs/$jobId'
      preLoaderRoute: typeof OrgOrgIdJobsJobIdRouteImport
      parentRoute: typeof OrgOrgIdRoute
    }
    '/org/$orgId/organization/job-templates/': {
      id: '/org/$orgId/organization/job-templates/'
      path: '/'
      fullPath: '/org/$orgId/organization/job-templates/'
      preLoaderRoute: typeof OrgOrgIdOrganizationJobTemplatesIndexRouteImport
      parentRoute: typeof OrgOrgIdOrganizationJobTemplatesRoute
    }
    '/org/$orgId/organization/interviews/': {
      id: '/org/$orgId/organization/interviews/'
      path: '/'
      fullPath: '/org/$orgId/organization/interviews/'
      preLoaderRoute: typeof OrgOrgIdOrganizationInterviewsIndexRouteImport
      parentRoute: typeof OrgOrgIdOrganizationInterviewsRoute
    }
    '/org/$orgId/organization/interview-plans/': {
      id: '/org/$orgId/organization/interview-plans/'
      path: '/'
      fullPath: '/org/$orgId/organization/interview-plans/'
      preLoaderRoute: typeof OrgOrgIdOrganizationInterviewPlansIndexRouteImport
      parentRoute: typeof OrgOrgIdOrganizationInterviewPlansRoute
    }
    '/org/$orgId/organization/feedback-forms/': {
      id: '/org/$orgId/organization/feedback-forms/'
      path: '/feedback-forms'
      fullPath: '/org/$orgId/organization/feedback-forms'
      preLoaderRoute: typeof OrgOrgIdOrganizationFeedbackFormsIndexRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/organization/application-forms/': {
      id: '/org/$orgId/organization/application-forms/'
      path: '/application-forms'
      fullPath: '/org/$orgId/organization/application-forms'
      preLoaderRoute: typeof OrgOrgIdOrganizationApplicationFormsIndexRouteImport
      parentRoute: typeof OrgOrgIdOrganizationRoute
    }
    '/org/$orgId/jobs/$jobId/pipeline': {
      id: '/org/$orgId/jobs/$jobId/pipeline'
      path: '/pipeline'
      fullPath: '/org/$orgId/jobs/$jobId/pipeline'
      preLoaderRoute: typeof OrgOrgIdJobsJobIdPipelineRouteImport
      parentRoute: typeof OrgOrgIdJobsJobIdRoute
    }
    '/org/$orgId/jobs/$jobId/interview-plan': {
      id: '/org/$orgId/jobs/$jobId/interview-plan'
      path: '/interview-plan'
      fullPath: '/org/$orgId/jobs/$jobId/interview-plan'
      preLoaderRoute: typeof OrgOrgIdJobsJobIdInterviewPlanRouteImport
      parentRoute: typeof OrgOrgIdJobsJobIdRoute
    }
    '/org/$orgId/jobs/$jobId/hiring-team': {
      id: '/org/$orgId/jobs/$jobId/hiring-team'
      path: '/hiring-team'
      fullPath: '/org/$orgId/jobs/$jobId/hiring-team'
      preLoaderRoute: typeof OrgOrgIdJobsJobIdHiringTeamRouteImport
      parentRoute: typeof OrgOrgIdJobsJobIdRoute
    }
    '/org/$orgId/jobs/$jobId/details': {
      id: '/org/$orgId/jobs/$jobId/details'
      path: '/details'
      fullPath: '/org/$orgId/jobs/$jobId/details'
      preLoaderRoute: typeof OrgOrgIdJobsJobIdDetailsRouteImport
      parentRoute: typeof OrgOrgIdJobsJobIdRoute
    }
    '/org/$orgId/jobs/$jobId/description': {
      id: '/org/$orgId/jobs/$jobId/description'
      path: '/description'
      fullPath: '/org/$orgId/jobs/$jobId/description'
      preLoaderRoute: typeof OrgOrgIdJobsJobIdDescriptionRouteImport
      parentRoute: typeof OrgOrgIdJobsJobIdRoute
    }
    '/org/$orgId/jobs/$jobId/criteria': {
      id: '/org/$orgId/jobs/$jobId/criteria'
      path: '/criteria'
      fullPath: '/org/$orgId/jobs/$jobId/criteria'
      preLoaderRoute: typeof OrgOrgIdJobsJobIdCriteriaRouteImport
      parentRoute: typeof OrgOrgIdJobsJobIdRoute
    }
    '/org/$orgId/jobs/$jobId/application-form': {
      id: '/org/$orgId/jobs/$jobId/application-form'
      path: '/application-form'
      fullPath: '/org/$orgId/jobs/$jobId/application-form'
      preLoaderRoute: typeof OrgOrgIdJobsJobIdApplicationFormRouteImport
      parentRoute: typeof OrgOrgIdJobsJobIdRoute
    }
  }
}

interface OrgOrgIdOrganizationInterviewPlansRouteChildren {
  OrgOrgIdOrganizationInterviewPlansIndexRoute: typeof OrgOrgIdOrganizationInterviewPlansIndexRoute
}

const OrgOrgIdOrganizationInterviewPlansRouteChildren: OrgOrgIdOrganizationInterviewPlansRouteChildren =
  {
    OrgOrgIdOrganizationInterviewPlansIndexRoute:
      OrgOrgIdOrganizationInterviewPlansIndexRoute,
  }

const OrgOrgIdOrganizationInterviewPlansRouteWithChildren =
  OrgOrgIdOrganizationInterviewPlansRoute._addFileChildren(
    OrgOrgIdOrganizationInterviewPlansRouteChildren,
  )

interface OrgOrgIdOrganizationInterviewsRouteChildren {
  OrgOrgIdOrganizationInterviewsIndexRoute: typeof OrgOrgIdOrganizationInterviewsIndexRoute
}

const OrgOrgIdOrganizationInterviewsRouteChildren: OrgOrgIdOrganizationInterviewsRouteChildren =
  {
    OrgOrgIdOrganizationInterviewsIndexRoute:
      OrgOrgIdOrganizationInterviewsIndexRoute,
  }

const OrgOrgIdOrganizationInterviewsRouteWithChildren =
  OrgOrgIdOrganizationInterviewsRoute._addFileChildren(
    OrgOrgIdOrganizationInterviewsRouteChildren,
  )

interface OrgOrgIdOrganizationJobTemplatesRouteChildren {
  OrgOrgIdOrganizationJobTemplatesIndexRoute: typeof OrgOrgIdOrganizationJobTemplatesIndexRoute
}

const OrgOrgIdOrganizationJobTemplatesRouteChildren: OrgOrgIdOrganizationJobTemplatesRouteChildren =
  {
    OrgOrgIdOrganizationJobTemplatesIndexRoute:
      OrgOrgIdOrganizationJobTemplatesIndexRoute,
  }

const OrgOrgIdOrganizationJobTemplatesRouteWithChildren =
  OrgOrgIdOrganizationJobTemplatesRoute._addFileChildren(
    OrgOrgIdOrganizationJobTemplatesRouteChildren,
  )

interface OrgOrgIdOrganizationRouteChildren {
  OrgOrgIdOrganizationArchiveReasonsRoute: typeof OrgOrgIdOrganizationArchiveReasonsRoute
  OrgOrgIdOrganizationCloseReasonsRoute: typeof OrgOrgIdOrganizationCloseReasonsRoute
  OrgOrgIdOrganizationCompanyRoute: typeof OrgOrgIdOrganizationCompanyRoute
  OrgOrgIdOrganizationCustomFieldsRoute: typeof OrgOrgIdOrganizationCustomFieldsRoute
  OrgOrgIdOrganizationDataPrivacyRoute: typeof OrgOrgIdOrganizationDataPrivacyRoute
  OrgOrgIdOrganizationDepartmentsRoute: typeof OrgOrgIdOrganizationDepartmentsRoute
  OrgOrgIdOrganizationEmailTemplatesRoute: typeof OrgOrgIdOrganizationEmailTemplatesRoute
  OrgOrgIdOrganizationFundsRoute: typeof OrgOrgIdOrganizationFundsRoute
  OrgOrgIdOrganizationInterviewPlansRoute: typeof OrgOrgIdOrganizationInterviewPlansRouteWithChildren
  OrgOrgIdOrganizationInterviewReasonsRoute: typeof OrgOrgIdOrganizationInterviewReasonsRoute
  OrgOrgIdOrganizationInterviewsRoute: typeof OrgOrgIdOrganizationInterviewsRouteWithChildren
  OrgOrgIdOrganizationJobTemplatesRoute: typeof OrgOrgIdOrganizationJobTemplatesRouteWithChildren
  OrgOrgIdOrganizationLocationsRoute: typeof OrgOrgIdOrganizationLocationsRoute
  OrgOrgIdOrganizationMembersRoute: typeof OrgOrgIdOrganizationMembersRoute
  OrgOrgIdOrganizationTagsRoute: typeof OrgOrgIdOrganizationTagsRoute
  OrgOrgIdOrganizationIndexRoute: typeof OrgOrgIdOrganizationIndexRoute
  OrgOrgIdOrganizationApplicationFormsIndexRoute: typeof OrgOrgIdOrganizationApplicationFormsIndexRoute
  OrgOrgIdOrganizationFeedbackFormsIndexRoute: typeof OrgOrgIdOrganizationFeedbackFormsIndexRoute
}

const OrgOrgIdOrganizationRouteChildren: OrgOrgIdOrganizationRouteChildren = {
  OrgOrgIdOrganizationArchiveReasonsRoute:
    OrgOrgIdOrganizationArchiveReasonsRoute,
  OrgOrgIdOrganizationCloseReasonsRoute: OrgOrgIdOrganizationCloseReasonsRoute,
  OrgOrgIdOrganizationCompanyRoute: OrgOrgIdOrganizationCompanyRoute,
  OrgOrgIdOrganizationCustomFieldsRoute: OrgOrgIdOrganizationCustomFieldsRoute,
  OrgOrgIdOrganizationDataPrivacyRoute: OrgOrgIdOrganizationDataPrivacyRoute,
  OrgOrgIdOrganizationDepartmentsRoute: OrgOrgIdOrganizationDepartmentsRoute,
  OrgOrgIdOrganizationEmailTemplatesRoute:
    OrgOrgIdOrganizationEmailTemplatesRoute,
  OrgOrgIdOrganizationFundsRoute: OrgOrgIdOrganizationFundsRoute,
  OrgOrgIdOrganizationInterviewPlansRoute:
    OrgOrgIdOrganizationInterviewPlansRouteWithChildren,
  OrgOrgIdOrganizationInterviewReasonsRoute:
    OrgOrgIdOrganizationInterviewReasonsRoute,
  OrgOrgIdOrganizationInterviewsRoute:
    OrgOrgIdOrganizationInterviewsRouteWithChildren,
  OrgOrgIdOrganizationJobTemplatesRoute:
    OrgOrgIdOrganizationJobTemplatesRouteWithChildren,
  OrgOrgIdOrganizationLocationsRoute: OrgOrgIdOrganizationLocationsRoute,
  OrgOrgIdOrganizationMembersRoute: OrgOrgIdOrganizationMembersRoute,
  OrgOrgIdOrganizationTagsRoute: OrgOrgIdOrganizationTagsRoute,
  OrgOrgIdOrganizationIndexRoute: OrgOrgIdOrganizationIndexRoute,
  OrgOrgIdOrganizationApplicationFormsIndexRoute:
    OrgOrgIdOrganizationApplicationFormsIndexRoute,
  OrgOrgIdOrganizationFeedbackFormsIndexRoute:
    OrgOrgIdOrganizationFeedbackFormsIndexRoute,
}

const OrgOrgIdOrganizationRouteWithChildren =
  OrgOrgIdOrganizationRoute._addFileChildren(OrgOrgIdOrganizationRouteChildren)

interface OrgOrgIdSettingsRouteChildren {
  OrgOrgIdSettingsCalendarRoute: typeof OrgOrgIdSettingsCalendarRoute
  OrgOrgIdSettingsIndexRoute: typeof OrgOrgIdSettingsIndexRoute
}

const OrgOrgIdSettingsRouteChildren: OrgOrgIdSettingsRouteChildren = {
  OrgOrgIdSettingsCalendarRoute: OrgOrgIdSettingsCalendarRoute,
  OrgOrgIdSettingsIndexRoute: OrgOrgIdSettingsIndexRoute,
}

const OrgOrgIdSettingsRouteWithChildren =
  OrgOrgIdSettingsRoute._addFileChildren(OrgOrgIdSettingsRouteChildren)

interface OrgOrgIdJobsJobIdRouteChildren {
  OrgOrgIdJobsJobIdApplicationFormRoute: typeof OrgOrgIdJobsJobIdApplicationFormRoute
  OrgOrgIdJobsJobIdCriteriaRoute: typeof OrgOrgIdJobsJobIdCriteriaRoute
  OrgOrgIdJobsJobIdDescriptionRoute: typeof OrgOrgIdJobsJobIdDescriptionRoute
  OrgOrgIdJobsJobIdDetailsRoute: typeof OrgOrgIdJobsJobIdDetailsRoute
  OrgOrgIdJobsJobIdHiringTeamRoute: typeof OrgOrgIdJobsJobIdHiringTeamRoute
  OrgOrgIdJobsJobIdInterviewPlanRoute: typeof OrgOrgIdJobsJobIdInterviewPlanRoute
  OrgOrgIdJobsJobIdPipelineRoute: typeof OrgOrgIdJobsJobIdPipelineRoute
}

const OrgOrgIdJobsJobIdRouteChildren: OrgOrgIdJobsJobIdRouteChildren = {
  OrgOrgIdJobsJobIdApplicationFormRoute: OrgOrgIdJobsJobIdApplicationFormRoute,
  OrgOrgIdJobsJobIdCriteriaRoute: OrgOrgIdJobsJobIdCriteriaRoute,
  OrgOrgIdJobsJobIdDescriptionRoute: OrgOrgIdJobsJobIdDescriptionRoute,
  OrgOrgIdJobsJobIdDetailsRoute: OrgOrgIdJobsJobIdDetailsRoute,
  OrgOrgIdJobsJobIdHiringTeamRoute: OrgOrgIdJobsJobIdHiringTeamRoute,
  OrgOrgIdJobsJobIdInterviewPlanRoute: OrgOrgIdJobsJobIdInterviewPlanRoute,
  OrgOrgIdJobsJobIdPipelineRoute: OrgOrgIdJobsJobIdPipelineRoute,
}

const OrgOrgIdJobsJobIdRouteWithChildren =
  OrgOrgIdJobsJobIdRoute._addFileChildren(OrgOrgIdJobsJobIdRouteChildren)

interface OrgOrgIdRouteChildren {
  OrgOrgIdOrganizationRoute: typeof OrgOrgIdOrganizationRouteWithChildren
  OrgOrgIdPipelineRoute: typeof OrgOrgIdPipelineRoute
  OrgOrgIdSettingsRoute: typeof OrgOrgIdSettingsRouteWithChildren
  OrgOrgIdIndexRoute: typeof OrgOrgIdIndexRoute
  OrgOrgIdJobsJobIdRoute: typeof OrgOrgIdJobsJobIdRouteWithChildren
  OrgOrgIdJobsIndexRoute: typeof OrgOrgIdJobsIndexRoute
}

const OrgOrgIdRouteChildren: OrgOrgIdRouteChildren = {
  OrgOrgIdOrganizationRoute: OrgOrgIdOrganizationRouteWithChildren,
  OrgOrgIdPipelineRoute: OrgOrgIdPipelineRoute,
  OrgOrgIdSettingsRoute: OrgOrgIdSettingsRouteWithChildren,
  OrgOrgIdIndexRoute: OrgOrgIdIndexRoute,
  OrgOrgIdJobsJobIdRoute: OrgOrgIdJobsJobIdRouteWithChildren,
  OrgOrgIdJobsIndexRoute: OrgOrgIdJobsIndexRoute,
}

const OrgOrgIdRouteWithChildren = OrgOrgIdRoute._addFileChildren(
  OrgOrgIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  OrgOrgIdRoute: OrgOrgIdRouteWithChildren,
  OrgCreateRoute: OrgCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
