/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as EncryptionRouteImport } from './routes/encryption'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as AiTermsRouteImport } from './routes/ai-terms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as OrgSplatRouteImport } from './routes/org/$'
import { Route as CareersOrgSlugRouteImport } from './routes/careers/$orgSlug'
import { Route as CareersOrgSlugIndexRouteImport } from './routes/careers/$orgSlug/index'
import { Route as CareersOrgSlugJobsPostingSlugRouteImport } from './routes/careers/$orgSlug/jobs/$postingSlug'
import { Route as CareersOrgSlugJobsPostingSlugIndexRouteImport } from './routes/careers/$orgSlug/jobs/$postingSlug/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptionRoute = EncryptionRouteImport.update({
  id: '/encryption',
  path: '/encryption',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTermsRoute = AiTermsRouteImport.update({
  id: '/ai-terms',
  path: '/ai-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSplatRoute = OrgSplatRouteImport.update({
  id: '/org/$',
  path: '/org/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersOrgSlugRoute = CareersOrgSlugRouteImport.update({
  id: '/careers/$orgSlug',
  path: '/careers/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersOrgSlugIndexRoute = CareersOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersOrgSlugRoute,
} as any)
const CareersOrgSlugJobsPostingSlugRoute =
  CareersOrgSlugJobsPostingSlugRouteImport.update({
    id: '/jobs/$postingSlug',
    path: '/jobs/$postingSlug',
    getParentRoute: () => CareersOrgSlugRoute,
  } as any)
const CareersOrgSlugJobsPostingSlugIndexRoute =
  CareersOrgSlugJobsPostingSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CareersOrgSlugJobsPostingSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-terms': typeof AiTermsRoute
  '/dpa': typeof DpaRoute
  '/encryption': typeof EncryptionRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/careers/$orgSlug': typeof CareersOrgSlugRouteWithChildren
  '/org/$': typeof OrgSplatRoute
  '/jobs': typeof JobsIndexRoute
  '/careers/$orgSlug/': typeof CareersOrgSlugIndexRoute
  '/careers/$orgSlug/jobs/$postingSlug': typeof CareersOrgSlugJobsPostingSlugRouteWithChildren
  '/careers/$orgSlug/jobs/$postingSlug/': typeof CareersOrgSlugJobsPostingSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-terms': typeof AiTermsRoute
  '/dpa': typeof DpaRoute
  '/encryption': typeof EncryptionRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/org/$': typeof OrgSplatRoute
  '/jobs': typeof JobsIndexRoute
  '/careers/$orgSlug': typeof CareersOrgSlugIndexRoute
  '/careers/$orgSlug/jobs/$postingSlug': typeof CareersOrgSlugJobsPostingSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-terms': typeof AiTermsRoute
  '/dpa': typeof DpaRoute
  '/encryption': typeof EncryptionRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/careers/$orgSlug': typeof CareersOrgSlugRouteWithChildren
  '/org/$': typeof OrgSplatRoute
  '/jobs/': typeof JobsIndexRoute
  '/careers/$orgSlug/': typeof CareersOrgSlugIndexRoute
  '/careers/$orgSlug/jobs/$postingSlug': typeof CareersOrgSlugJobsPostingSlugRouteWithChildren
  '/careers/$orgSlug/jobs/$postingSlug/': typeof CareersOrgSlugJobsPostingSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-terms'
    | '/dpa'
    | '/encryption'
    | '/invite'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/careers/$orgSlug'
    | '/org/$'
    | '/jobs'
    | '/careers/$orgSlug/'
    | '/careers/$orgSlug/jobs/$postingSlug'
    | '/careers/$orgSlug/jobs/$postingSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-terms'
    | '/dpa'
    | '/encryption'
    | '/invite'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/org/$'
    | '/jobs'
    | '/careers/$orgSlug'
    | '/careers/$orgSlug/jobs/$postingSlug'
  id:
    | '__root__'
    | '/'
    | '/ai-terms'
    | '/dpa'
    | '/encryption'
    | '/invite'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/careers/$orgSlug'
    | '/org/$'
    | '/jobs/'
    | '/careers/$orgSlug/'
    | '/careers/$orgSlug/jobs/$postingSlug'
    | '/careers/$orgSlug/jobs/$postingSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiTermsRoute: typeof AiTermsRoute
  DpaRoute: typeof DpaRoute
  EncryptionRoute: typeof EncryptionRoute
  InviteRoute: typeof InviteRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CareersOrgSlugRoute: typeof CareersOrgSlugRouteWithChildren
  OrgSplatRoute: typeof OrgSplatRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encryption': {
      id: '/encryption'
      path: '/encryption'
      fullPath: '/encryption'
      preLoaderRoute: typeof EncryptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-terms': {
      id: '/ai-terms'
      path: '/ai-terms'
      fullPath: '/ai-terms'
      preLoaderRoute: typeof AiTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$': {
      id: '/org/$'
      path: '/org/$'
      fullPath: '/org/$'
      preLoaderRoute: typeof OrgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$orgSlug': {
      id: '/careers/$orgSlug'
      path: '/careers/$orgSlug'
      fullPath: '/careers/$orgSlug'
      preLoaderRoute: typeof CareersOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$orgSlug/': {
      id: '/careers/$orgSlug/'
      path: '/'
      fullPath: '/careers/$orgSlug/'
      preLoaderRoute: typeof CareersOrgSlugIndexRouteImport
      parentRoute: typeof CareersOrgSlugRoute
    }
    '/careers/$orgSlug/jobs/$postingSlug': {
      id: '/careers/$orgSlug/jobs/$postingSlug'
      path: '/jobs/$postingSlug'
      fullPath: '/careers/$orgSlug/jobs/$postingSlug'
      preLoaderRoute: typeof CareersOrgSlugJobsPostingSlugRouteImport
      parentRoute: typeof CareersOrgSlugRoute
    }
    '/careers/$orgSlug/jobs/$postingSlug/': {
      id: '/careers/$orgSlug/jobs/$postingSlug/'
      path: '/'
      fullPath: '/careers/$orgSlug/jobs/$postingSlug/'
      preLoaderRoute: typeof CareersOrgSlugJobsPostingSlugIndexRouteImport
      parentRoute: typeof CareersOrgSlugJobsPostingSlugRoute
    }
  }
}

interface CareersOrgSlugJobsPostingSlugRouteChildren {
  CareersOrgSlugJobsPostingSlugIndexRoute: typeof CareersOrgSlugJobsPostingSlugIndexRoute
}

const CareersOrgSlugJobsPostingSlugRouteChildren: CareersOrgSlugJobsPostingSlugRouteChildren =
  {
    CareersOrgSlugJobsPostingSlugIndexRoute:
      CareersOrgSlugJobsPostingSlugIndexRoute,
  }

const CareersOrgSlugJobsPostingSlugRouteWithChildren =
  CareersOrgSlugJobsPostingSlugRoute._addFileChildren(
    CareersOrgSlugJobsPostingSlugRouteChildren,
  )

interface CareersOrgSlugRouteChildren {
  CareersOrgSlugIndexRoute: typeof CareersOrgSlugIndexRoute
  CareersOrgSlugJobsPostingSlugRoute: typeof CareersOrgSlugJobsPostingSlugRouteWithChildren
}

const CareersOrgSlugRouteChildren: CareersOrgSlugRouteChildren = {
  CareersOrgSlugIndexRoute: CareersOrgSlugIndexRoute,
  CareersOrgSlugJobsPostingSlugRoute:
    CareersOrgSlugJobsPostingSlugRouteWithChildren,
}

const CareersOrgSlugRouteWithChildren = CareersOrgSlugRoute._addFileChildren(
  CareersOrgSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiTermsRoute: AiTermsRoute,
  DpaRoute: DpaRoute,
  EncryptionRoute: EncryptionRoute,
  InviteRoute: InviteRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CareersOrgSlugRoute: CareersOrgSlugRouteWithChildren,
  OrgSplatRoute: OrgSplatRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
