/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ScheduleTokenRouteImport } from './routes/schedule/$token'
import { Route as CareersOrgSlugRouteImport } from './routes/careers/$orgSlug'
import { Route as CareersOrgSlugIndexRouteImport } from './routes/careers/$orgSlug/index'
import { Route as CareersOrgSlugJobsPostingSlugRouteImport } from './routes/careers/$orgSlug/jobs/$postingSlug'
import { Route as CareersOrgSlugJobsPostingSlugIndexRouteImport } from './routes/careers/$orgSlug/jobs/$postingSlug/index'
import { Route as CareersOrgSlugJobsPostingSlugApplyRouteImport } from './routes/careers/$orgSlug/jobs/$postingSlug/apply'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleTokenRoute = ScheduleTokenRouteImport.update({
  id: '/schedule/$token',
  path: '/schedule/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersOrgSlugRoute = CareersOrgSlugRouteImport.update({
  id: '/careers/$orgSlug',
  path: '/careers/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersOrgSlugIndexRoute = CareersOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersOrgSlugRoute,
} as any)
const CareersOrgSlugJobsPostingSlugRoute =
  CareersOrgSlugJobsPostingSlugRouteImport.update({
    id: '/jobs/$postingSlug',
    path: '/jobs/$postingSlug',
    getParentRoute: () => CareersOrgSlugRoute,
  } as any)
const CareersOrgSlugJobsPostingSlugIndexRoute =
  CareersOrgSlugJobsPostingSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CareersOrgSlugJobsPostingSlugRoute,
  } as any)
const CareersOrgSlugJobsPostingSlugApplyRoute =
  CareersOrgSlugJobsPostingSlugApplyRouteImport.update({
    id: '/apply',
    path: '/apply',
    getParentRoute: () => CareersOrgSlugJobsPostingSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/applications': typeof ApplicationsRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/careers/$orgSlug': typeof CareersOrgSlugRouteWithChildren
  '/schedule/$token': typeof ScheduleTokenRoute
  '/jobs': typeof JobsIndexRoute
  '/careers/$orgSlug/': typeof CareersOrgSlugIndexRoute
  '/careers/$orgSlug/jobs/$postingSlug': typeof CareersOrgSlugJobsPostingSlugRouteWithChildren
  '/careers/$orgSlug/jobs/$postingSlug/apply': typeof CareersOrgSlugJobsPostingSlugApplyRoute
  '/careers/$orgSlug/jobs/$postingSlug/': typeof CareersOrgSlugJobsPostingSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/applications': typeof ApplicationsRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/jobs': typeof JobsIndexRoute
  '/careers/$orgSlug': typeof CareersOrgSlugIndexRoute
  '/careers/$orgSlug/jobs/$postingSlug/apply': typeof CareersOrgSlugJobsPostingSlugApplyRoute
  '/careers/$orgSlug/jobs/$postingSlug': typeof CareersOrgSlugJobsPostingSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/applications': typeof ApplicationsRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/careers/$orgSlug': typeof CareersOrgSlugRouteWithChildren
  '/schedule/$token': typeof ScheduleTokenRoute
  '/jobs/': typeof JobsIndexRoute
  '/careers/$orgSlug/': typeof CareersOrgSlugIndexRoute
  '/careers/$orgSlug/jobs/$postingSlug': typeof CareersOrgSlugJobsPostingSlugRouteWithChildren
  '/careers/$orgSlug/jobs/$postingSlug/apply': typeof CareersOrgSlugJobsPostingSlugApplyRoute
  '/careers/$orgSlug/jobs/$postingSlug/': typeof CareersOrgSlugJobsPostingSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/applications'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/careers/$orgSlug'
    | '/schedule/$token'
    | '/jobs'
    | '/careers/$orgSlug/'
    | '/careers/$orgSlug/jobs/$postingSlug'
    | '/careers/$orgSlug/jobs/$postingSlug/apply'
    | '/careers/$orgSlug/jobs/$postingSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/applications'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/schedule/$token'
    | '/jobs'
    | '/careers/$orgSlug'
    | '/careers/$orgSlug/jobs/$postingSlug/apply'
    | '/careers/$orgSlug/jobs/$postingSlug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/applications'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/careers/$orgSlug'
    | '/schedule/$token'
    | '/jobs/'
    | '/careers/$orgSlug/'
    | '/careers/$orgSlug/jobs/$postingSlug'
    | '/careers/$orgSlug/jobs/$postingSlug/apply'
    | '/careers/$orgSlug/jobs/$postingSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ApplicationsRoute: typeof ApplicationsRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  CareersOrgSlugRoute: typeof CareersOrgSlugRouteWithChildren
  ScheduleTokenRoute: typeof ScheduleTokenRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$token': {
      id: '/schedule/$token'
      path: '/schedule/$token'
      fullPath: '/schedule/$token'
      preLoaderRoute: typeof ScheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$orgSlug': {
      id: '/careers/$orgSlug'
      path: '/careers/$orgSlug'
      fullPath: '/careers/$orgSlug'
      preLoaderRoute: typeof CareersOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$orgSlug/': {
      id: '/careers/$orgSlug/'
      path: '/'
      fullPath: '/careers/$orgSlug/'
      preLoaderRoute: typeof CareersOrgSlugIndexRouteImport
      parentRoute: typeof CareersOrgSlugRoute
    }
    '/careers/$orgSlug/jobs/$postingSlug': {
      id: '/careers/$orgSlug/jobs/$postingSlug'
      path: '/jobs/$postingSlug'
      fullPath: '/careers/$orgSlug/jobs/$postingSlug'
      preLoaderRoute: typeof CareersOrgSlugJobsPostingSlugRouteImport
      parentRoute: typeof CareersOrgSlugRoute
    }
    '/careers/$orgSlug/jobs/$postingSlug/': {
      id: '/careers/$orgSlug/jobs/$postingSlug/'
      path: '/'
      fullPath: '/careers/$orgSlug/jobs/$postingSlug/'
      preLoaderRoute: typeof CareersOrgSlugJobsPostingSlugIndexRouteImport
      parentRoute: typeof CareersOrgSlugJobsPostingSlugRoute
    }
    '/careers/$orgSlug/jobs/$postingSlug/apply': {
      id: '/careers/$orgSlug/jobs/$postingSlug/apply'
      path: '/apply'
      fullPath: '/careers/$orgSlug/jobs/$postingSlug/apply'
      preLoaderRoute: typeof CareersOrgSlugJobsPostingSlugApplyRouteImport
      parentRoute: typeof CareersOrgSlugJobsPostingSlugRoute
    }
  }
}

interface CareersOrgSlugJobsPostingSlugRouteChildren {
  CareersOrgSlugJobsPostingSlugApplyRoute: typeof CareersOrgSlugJobsPostingSlugApplyRoute
  CareersOrgSlugJobsPostingSlugIndexRoute: typeof CareersOrgSlugJobsPostingSlugIndexRoute
}

const CareersOrgSlugJobsPostingSlugRouteChildren: CareersOrgSlugJobsPostingSlugRouteChildren =
  {
    CareersOrgSlugJobsPostingSlugApplyRoute:
      CareersOrgSlugJobsPostingSlugApplyRoute,
    CareersOrgSlugJobsPostingSlugIndexRoute:
      CareersOrgSlugJobsPostingSlugIndexRoute,
  }

const CareersOrgSlugJobsPostingSlugRouteWithChildren =
  CareersOrgSlugJobsPostingSlugRoute._addFileChildren(
    CareersOrgSlugJobsPostingSlugRouteChildren,
  )

interface CareersOrgSlugRouteChildren {
  CareersOrgSlugIndexRoute: typeof CareersOrgSlugIndexRoute
  CareersOrgSlugJobsPostingSlugRoute: typeof CareersOrgSlugJobsPostingSlugRouteWithChildren
}

const CareersOrgSlugRouteChildren: CareersOrgSlugRouteChildren = {
  CareersOrgSlugIndexRoute: CareersOrgSlugIndexRoute,
  CareersOrgSlugJobsPostingSlugRoute:
    CareersOrgSlugJobsPostingSlugRouteWithChildren,
}

const CareersOrgSlugRouteWithChildren = CareersOrgSlugRoute._addFileChildren(
  CareersOrgSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ApplicationsRoute: ApplicationsRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  CareersOrgSlugRoute: CareersOrgSlugRouteWithChildren,
  ScheduleTokenRoute: ScheduleTokenRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
